url: "https://lucasprag.com"
baseurl: ""
title: "Lucas Arantes"
description: "Blog about Ruby, Elixir, command line, text editors, developer productivity, personal projects, etc."
keyboards: "Lucasprag, Software Engineer, Elixir Developer, Side Projects, VSCode, Productivity, solopreneur, Command Line Productivity, Phoenix, React, Ruby on Rails"

collections:
  posts:
    permalink: '/posts/:title/'

plugins:
  - jekyll-postcss
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

postcss:
  cache: false