url: "https://lucasprag.com"
baseurl: ""
title: "Lucas Arantes"
description: "Blog about Ruby, Elixir, command line, text editors, developer productivity, personal projects, etc."

collections:
  posts:
    permalink: '/posts/:title/'

plugins:
  - jekyll-postcss
  - jekyll-feed
  - jekyll-sitemap

postcss:
  cache: false